### ISSUE TITLE
Bug: Some weird transitions are taking place

### ISSUE THREAD

**Issue by harish-sethuraman** [eslint/eslint.org#400] opened 2023-01-07 18:58 UTC
### URL(s)

https://eslint.org
https://zh-hans.eslint.org/

### What did you do?

Seems like in the english site there is no lag when we resize the tab. But when I did the same for chinese site and hindi site it didnt work well. It was lagging and transition was taking time to get applied.

https://user-images.githubusercontent.com/32865581/211166307-06f49108-ca53-4084-a1bd-53b155b9fc8a.mov

### What did you expect to happen?

Every translation site should be similar to main site and shouldnt have resize transitions

### What actually happened?

weird transitions were taking place

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by shanpriyan** [comment] 2023-01-07 20:01
I think this is a browser specific issue because I'm not able to reproduce it in Chrome on Ubuntu 🤔

**Comment by harish-sethuraman** [comment] 2023-01-07 21:04
I used chrome on mac. Did you try opening the inspect tab and the. Resizing the inspect tab?

**Comment by siva-kannan3** [comment] 2023-01-08 02:08
I've also tested with Mac chrome and the issue exists. 
I ran a simple performance analysis on resizing with English and Chinese language. The report image is attached below:

English:
---
<img width="731" alt="image" src="https://user-images.githubusercontent.com/60533560/211177424-86d7692b-f35f-4343-ac71-ebb73a540846.png">

Chinese:
---
<img width="731" alt="image" src="https://user-images.githubusercontent.com/60533560/211177432-39d1f1bb-fea6-43db-9527-daa9d075ac31.png">

It seems rendering takes too much time.

**Comment by kecrily** [comment] 2023-01-08 06:29
I agree it's a browser specific issue. I can't reproduce it on Firefox or Safari on Mac, only Chrome. And I wonder if Chrome on Windows has this problem.

**Comment by shanpriyan** [comment] 2023-01-08 07:05
> I used chrome on mac. Did you try opening the inspect tab and the. Resizing the inspect tab?

Yes

**Comment by nzakas** [comment] 2023-01-12 21:12
This might actually be due to the text/font itself and have nothing to do with any code, per se. All of the HTML, CSS, and images are the same for all sites, the only difference is the text and font. We might just be running into a rendering issue with that.

I don't think there's anything we can do about this, nor do I think it's a particularly big deal to leave as-is.

**Comment by shanpriyan** [comment] 2023-01-21 08:12
> I agree it's a browser specific issue. I can't reproduce it on Firefox or Safari on Mac, only Chrome. And I wonder if Chrome on Windows has this problem.

Happens in chrome on windows too but there is no difference in languages, Lag happens for all languages at the same rate.

(we can ignore this issue https://github.com/eslint/eslint.org/issues/400#issuecomment-1380999238)

**Comment by nzakas** [comment] 2023-01-24 00:40
Closing as there’s nothing we can do.

**Closed by nzakas** 2023-01-24 00:40 UTC
Labels: bug, accepted
